'use client'

import type { PatternRendererProps } from './types'

export function ReportPattern({ fields, detail }: PatternRendererProps) {
  const agentName = detail.ai_config?.agent_name || 'System'
  const sections = fields.slice(0, 4)
  return (
    <div className="rounded-[7px] p-4" style={{ background: '#EDF2F7', border: '1px solid #E2E8F0' }}>
      {/* Document header */}
      <div className="mb-3 pb-2.5" style={{ borderBottom: '2px solid #044159' }}>
        <div className="text-[13px] font-bold" style={{ color: '#0A1E2F' }}>{detail.title || 'Report'}</div>
        <div className="text-[9px] mt-0.5" style={{ color: '#718096' }}>Generated {new Date().toLocaleDateString()} &middot; Confidential</div>
      </div>

      {/* Sections */}
      {sections.map((f, i) => (
        <div key={i} className="mb-3">
          <div className="text-[10px] font-semibold mb-1" style={{ color: '#044159' }}>{i + 1}. {f.name}</div>
          <div className="text-[9px] leading-relaxed" style={{ color: '#4A5568' }}>{f.mock_value}</div>
        </div>
      ))}

      {/* Footer */}
      <div className="pt-2.5 mt-3 flex items-center justify-between" style={{ borderTop: '1px solid #E2E8F0' }}>
        <span className="text-[8px]" style={{ color: '#A0AEC0' }}>Generated by {agentName}</span>
        <div className="flex gap-1.5">
          <button className="px-2.5 py-1 rounded-[5px] text-[9px] font-semibold text-white" style={{ background: '#3FAF7A' }}>Export PDF</button>
          <button className="px-2.5 py-1 rounded-[5px] text-[9px] font-semibold" style={{ background: '#fff', color: '#4A5568', border: '1px solid #E2E8F0' }}>Share</button>
        </div>
      </div>
    </div>
  )
}
