-- Epic overlay plan: stores the 4-flow tour data (vision epics, AI flow,
-- horizons, discovery threads) generated by the extended analysis pipeline.
ALTER TABLE prototypes ADD COLUMN IF NOT EXISTS epic_plan JSONB;
